var experiences = [
  {
    _id: "5eda9f05f5d5903260db5ecf",
    key: "1",
    location: "NIGHTLIFE.NEW YORK",
    name: "Discover the city's party scene",
    price: 35,
    person: 1,
    Features: [
      { isCancelationFlexibility: "true" },
      { isCancelationFlexibility: "false" },
    ],
    image: "https://imgur.com/kKa8jx6.png",
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 64, star: 5 }],
  },
  {
    _id: "5eda9f05f5d5903260db5ed0",
    key: "2",
    location: "ENTERTAINMENT.VANCOUVER",
    name: "Tour with an Enthusiastic Local!",
    price: 3,
    person: 1,
    image: "https://imgur.com/erMnCYd.png",
    Features: [
      { isCancelationFlexibility: "true" },
      { isCancelationFlexibility: "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 1, star: 5 }],
  },
  {
    _id: "5eda9f05f5d5903260db5ed1",
    key: "3",
    location: "PHOTO CLASS.LOS ANGELES",
    name: "Must Have L.A. Pictures!",
    price: 39,
    person: 1,
    image: "https://imgur.com/XcvVRun.png",
    Features: [
      { isCancelationFlexibility: "true" },
      { isCancelationFlexibility: "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 179, star: 5 }],
  },
  {
    _id: "5eda9f05f5d5903260db5ed2",
    key: "4",
    location: "PHOTOGRAPHY.NEW YORK",
    name: "Retro Photoshoot in NYC",
    price: 72,
    person: 1,
    image: "https://imgur.com/QQ5nHi9.png",
    Features: [
      { isCancelationFlexibility: "true" },
      { isCancelationFlexibility: "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 72, star: 5 }],
  },
  {
    _id: "5eda9f05f5d5903260db5ed3",
    key: "5",
    location: "GLASS BRIDGE.CHINA",
    name: "Glass Bridge",
    price: 35,
    person: 1,
    image: "https://imgur.com/mHidbNC.png",
    Features: [
      { isCancelationFlexibility: "true" },
      { isCancelationFlexibility: "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 84, star: 5 }],
  },
  {
    _id: "5eda9f05f5d5903260db5ed4",
    key: "6",
    location: "PHOTO SHOOT.PARIS",
    name: "Photo shoot in Paris",
    price: 120,
    person: 1,
    image: "https://imgur.com/fb09Qh6.png",
    Features: [
      { isCancelationFlexibility: "true" },
      { isCancelationFlexibility: "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 50, star: 5 }],
  },
];
