var home = 

[
  {
    _id: "5eda9e73fbf3943a1898a4bf",
    key: "1",
    location: "NIGHTLIFE.NEW YORK",
    name: "Unique Cob Cottage",
    category: "Cottage",
    price: 128,
    person: 1,
    mainFeatures: [{ Bed: 2, bath: 2, Guests: 4 }],
    Features: [
      { "is cancelationFlexibility": "true" },
      { "is cancelationFlexibility": "false" },
    ],
    image: "https://imgur.com/IKoNXNE.png",
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 284, star: 5 }],
  },
  {
    _id: "5eda9e73fbf3943a1898a4c0",
    key: "2",
    location: "NIGHTLIFE.NEW YORK",
    name: "The Joshua Tree House",
    category: "Flat",
    price: 250,
    person: 1,
    image: "https://imgur.com/0Z6MxTV.png",
    mainFeatures: [{ Bed: 2, bath: 2, Guests: 4 }],
    Features: [
      { "is cancelationFlexibility": "true" },
      { "is cancelationFlexibility": "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 269, star: 5 }],
  },
  {
    _id: "5eda9e73fbf3943a1898a4c1",
    key: "3",
    location: "NIGHTLIFE.NEW YORK",
    name: "A Pirate's Life For Me - Houseboat!",
    category: "Flat",
    price: 209,
    person: 1,
    image: "https://imgur.com/Dl2pZlG.png",
    Features: [
      { "is cancelationFlexibility": "true" },
      { "is cancelationFlexibility": "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 140, star: 5 }],
  },
  {
    _id: "5eda9e73fbf3943a1898a4c2",
    key: "4",
    location: "NIGHTLIFE.NEW YORK",
    name: "Cob Cottage",
    category: "Cottage",
    price: 120,
    person: 1,
    image: "https://imgur.com/6rUksQK.png",
    mainFeatures: [{ Bed: 2, bath: 2, Guests: 4 }],
    Features: [
      { "is cancelationFlexibility": "true" },
      { "is cancelationFlexibility": "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 284, star: 5 }],
  },
  {
    _id: "5eda9e73fbf3943a1898a4c3",
    key: "5",
    location: "NIGHTLIFE.NEW YORK",
    name: "Tree-House",
    category: "Flat",
    price: 120,
    person: 1,
    image: "https://imgur.com/I2X9i1b.png",
    mainFeatures: [{ Bed: 2, bath: 2, Guests: 4 }],
    Features: [
      { "is cancelationFlexibility": "true" },
      { "is cancelationFlexibility": "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 284, star: 5 }],
  },
  {
    _id: "5eda9e73fbf3943a1898a4c4",
    key: "6",
    location: "NIGHTLIFE.NEW YORK",
    name: "HillVilla",
    category: "Flat",
    price: 120,
    person: 1,
    image: "https://imgur.com/1BmNDqw.png",
    mainFeatures: [{ Bed: 2, bath: 2, Guests: 4 }],
    Features: [
      { "is cancelationFlexibility": "true" },
      { "is cancelationFlexibility": "false" },
    ],
    host: [
      { hostName: "Rowdra", image: "https://imgur.com/Gyu1TXZ.png" },
      { hostName: "John", image: "https://imgur.com/gK4s3ya.png" },
      { hostName: "Edward", image: "https://imgur.com/oGoc7Mo.png" },
    ],
    review: [{ count: 284, star: 5 }],
  },
];
